#server:
#  port: 8082

logging:
  level.ru: DEBUG
  file:
    name: out/log.txt

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8090

application:
  greetings:
    - '%s присоединяется к вашей пати'
    - 'Это он, это он - Ленинградский %s'
    - 'Чей–то слышен тихий топот... Это в чат заходит %s'
    - 'Дульсинея? Серафим? Нет же - %s!'
    - 'Часть силы той, что вечно хочет зла, и вечно совершает благо. Узнали? Это %s!'
    - 'Тепло и мягко, словно в детстве? Ещё бы -  %s по соседству!'
    - 'А вот к нам на огонёк заглянул опять %s'
    - 'Марсианский прибыл рейс, %s уже здесь!'
    - 'Можно вечно смотреть на три вещи: как течёт вода, как горит огонь и как играет %s'
    - 'Бойтесь лешие, русалки - в ваше царство входит %s'
    - 'Набирает силы Мордор - нам необходим %s'
    - 'Лада седан! Баклажан! К нам заходит %s'
    - 'Ого! Смотрите, кто к нам пожаловал. Это же %s!'
    - 'Дикий %s появился'
    - '%s уже здесь'
    - 'Ура! %s теперь с нами'
    - 'Добро пожаловать, %s! надеемся, ты к нам не без пиццы'
    - 'Рады встрече, %s'
    - 'Знакомьтесь, это %s'
    - 'Привет, %s поздоровайся со всеми'
